name: Auto-Approve

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check author
        run: |
          if [[ "${{ github.actor }}" == "cristianscript" ]]; then
            echo "Actor is the main author. Proceeding with auto-approval."
          else
            echo "Actor is not the main author. Merging is blocked."
            echo "The actor is ${{ github.actor }}"
            exit 1
          fi
      - name: Auto-approve
        if: github.actor == 'cristianscript'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
