name: Auto-Approve

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'cristianscript' # This checks if the user is 'cristianscript'
    steps:
      - name: Auto-approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
