name: Auto-Approve and Auto-Merge

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check author
        run: |
          if [[ "${{ github.actor }}" == "cristiantorresf" ]] || [[ "${{ github.actor }}" == "birproject" ]]; then
            echo "Actor ${{ github.actor }} is super admin and has all the powers to authorized for auto-approval. Proceeding. 😎😎😎😎"
          else
            echo "Actor is not authorized. Merging is blocked."
            echo "The actor ${{ github.actor }} has not permissions only super admins code owners can have this exclusive privilege 😎"
            exit 1
          fi
      - name: Auto-approve
        if: github.actor == 'cristiantorresf' || github.actor == 'birproject'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-merge
        if: github.actor == 'cristiantorresf' || github.actor == 'birproject'
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # You can change this to merge or rebase as you prefer
          commit-message-pattern: "{{title}} (#{{number}})" # Custom pattern for commit messages
          # Additional options can be set as needed
