name: Auto-Approve and Auto-Merge

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check author
        run: |
          if [[ "${{ github.actor }}" == "cristiantorresf" ]] || [[ "${{ github.actor }}" == "birproject" ]]; then
            echo "Actor ${{ github.actor }} is super admin and has all the powers to authorized for auto-approval. Proceeding. 😎😎😎😎"
          else
            echo "Actor is not authorized. Merging is blocked."
            echo "The actor ${{ github.actor }} has not permissions only super admins code owners can have this exclusive privilege 😎"
            exit 1
          fi
      - name: Auto-approve
        if: github.actor == 'cristiantorresf' || github.actor == 'birproject'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: automerge
        name: Auto-merge
        if: github.actor == 'cristiantorresf' || github.actor == 'birproject'
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_LABELS: "automerge,!work in progress 🔥"
          UPDATE_METHOD: "rebase"

