name: Auto Approve PR

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-approve PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Log the event to debug
            console.log(JSON.stringify(github.event.pull_request, null, 2));

            // Check if the PR is from "cristianscript" to auto-approve
            if (github.event.pull_request.user.login === 'cristianscript') {
              github.rest.pulls.createReview({
                owner: 'birproject',
                repo: 'backend',
                pull_number: github.event.pull_request.number,
                event: 'APPROVE'
              });
            }
