name: Pruebamesta Master Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: npm run test:unit
        run: npm run test:unit
